### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by devdelimited** [bengarvey/budget#2]
Hey Ben,
First off, congrats on the launch! I like the clean functional look, and I love to see local tech talent succeeding!

I noticed two minor things in regard to your Search Results. First, I searched for "Education" and noticed the data tends to overflow to the right (runs off the grid into the blue). Second (and more of a feature suggestion), it would be really nice to be able to sort the search results.

That's it - again, nice job!
-Tim

**Comment by bengarvey** [comment]
You're right, thanks.  Unfortunately, Philadelphia budgets their schools in an entirely different budget, so those costs are not in the visualization.

Sort is next on my list to add in.  Still trying to decide if I want to do that in the database or on the client.
